let nombre = "Jesus";
console.log(nombre);
let apellidos = "Reynaldo";
console.log(apellidos);
let estudiante = nombre.concat(" ", apellidos);
console.log(estudiante);
let estudianteMayus = estudiante.toUpperCase();
console.log(estudianteMayus);
let estudianteMinus = estudiante.toLowerCase();
console.log(estudianteMinus);
let numeroLetras = estudiante.length;
console.log(numeroLetras);
let primeraLetra = estudiante[estudiante.indexOf(nombre)];
console.log(primeraLetra);
let ultimaLetra = estudiante[estudiante.lastIndexOf(apellidos)];
console.log(ultimaLetra);
let elimarEspacio = estudiante.replace(/ /g, "");
console.log(elimarEspacio);
let contineNombre = estudiante.includes(nombre);
console.log(contineNombre);
